service: motorbike-shop-api

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    NODE_ENV: ${self:provider.stage}
    MONGODB_URI: ${env:MONGODB_URI}
    LOG_LEVEL: ${env:LOG_LEVEL, 'info'}
    LOG_STORAGE: cloudwatch
    LOG_TO_FILE: false
    AWS_REGION: us-east-1
    CLOUDWATCH_GROUP_NAME: /aws/lambda/${self:service}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpPort: 3000

functions:
  api:
    handler: src/interfaces/handlers/api.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

iamRoleStatements:
  - Effect: Allow
    Action:
      - logs:CreateLogGroup
      - logs:CreateLogStream
      - logs:PutLogEvents
    Resource: "arn:aws:logs:*:*:*" 